alias la="LC_ALL=C ls -a"
alias ll="LC_ALL=C ls -la"
alias dotfs="git --git-dir=$HOME/dotfiles --work-tree=$HOME"
alias vdotfs="GIT_DIR=$HOME/dotfiles GIT_WORK_TREE=$HOME nvim"
alias nvidia-settings="nvidia-settings --config=$XDG_CONFIG_HOME/nvidia/settings"
